spring:
  application:
    name: college-service
    
  datasource:
    url : jdbc:mysql://localhost:3306/db_college?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username : ${datasource.username}
    password : ${datasource.password}
  jpa:
    properties:
      hibernate:
        dialect: ${datasource.dialect}
        connection:
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode: true
    show-sql: true
    hibernate:
      ddl-auto: none
      
  config:
    import: optional:configserver:http://localhost:8888   
    
  profiles:
    active: dev
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka      

  
    
